name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Setup dockerize
      uses: zcong1993/setup-dockerize@v1.1.0
    - name: prepare
      run: |
        docker run -d --name redis -p 6379:6379 redis:latest
        docker run -d --name mongo -p 27017:27017 mongo:latest
    - name: yarn install, and test
      env:
        MONGO_URI: mongodb://localhost/cache-test
        REDIS_URI: redis://localhost
      run: |
        yarn
        dockerize -wait tcp://localhost:6379 -timeout 1m
        dockerize -wait tcp://localhost:27017 -timeout 1m
        yarn test:cov
